
#Theme
# Upstream colors {{{

# Special
resize_in_steps yes
window_padding_width 0
window_padding_height 0

background #14151e 
foreground #98b0d3 

# Black
color0 #1F1F28
color8 #2A2A37

# Red
color1 #E82424
color9 #FF5D62

# Green
color2  #76946A
color10 #98BB6C

# Yellow
color3  #FF9E3B
color11 #E6C384

# Blue
color4  #658594
color12 #7FB4CA

# Magenta
color5  #957FB8
color13 #D27E99

# Cyan
color6  #9CABCA
color14 #A3D4D5

# White
color7  #DCD7BA
color15 #DCD7BA

# Cursor
cursor #cbced3
cursor_text_color #a5b6cf
##}}}

# Selection highlight
selection_foreground #a5b6cf
selection_background #1c1e27

#Fonts
font_family	JetBrainsMono Nerd Font
font_bold	auto
font_italic	auto
bold_italic_font auto

font_size 15

disable_ligature never

background_opacity 0.75

#TAB
tab_bar_style powerline
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold

#Bind
map ctrl+shift+k       next_tab
map ctrl+shift+j       previous_tab
