#################################
#           Animations         #
#################################
animations = true;
animation-stiffness = 100;
animation-stiffness-in-tag = 100;
animation-stiffness-tag-change = 90.0;

animation-window-mass = 0.3;
animation-dampening = 10;
animation-clamping = true;

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";

animation-open-exclude = [
  "class_g = 'Rofi'"
];

animation-unmap-exclude = [
  "class_g = 'Rofi'"
];


#################################
#             Corners           #
#################################
corner-radius = 8;
rounded-corners-exclude = [
  "name = 'Notification area'",
  "class_g = 'Polybar'",
  "class_g = 'Thunderbird'",
];
round-borders = 1;
round-borders-exclude = [
  #"class_g = 'TelegramDesktop'",
];

#################################
#             Shadows           #
#################################

shadow = true;
shadow-radius = 15;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.2;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'kitty'",
  "class_g = 'firefox'",
  "class_g = 'slop'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 8;

fade-exclude = [
  "class_g = 'firefox'"
]

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 1;

frame-opacity = 1.0;

inactive-opacity-override = false;

active-opacity = 1;

opacity-rule = [
   "100:name     = 'Dunst'",
  "80:class_g     = 'Polybar'",
];

#################################
#     Background-Blurring       #
#################################

nimations=true;
fade-delta= 5;

blur: {
	method = "dual_kawase";
	strength = 10;
	deviation = 1;
	background-frame = true;
	background-fixed = true;
	kern = "11x11gaussian";
}

blur-whitelist = false;

blur-exclude = [
  "class_g = 'TelegramDesktop'",
  "class_g = 'firefox'"
];


#################################
#       General Settings        #
#################################

backend = "glx";
use-damage = false;
unredir-if-possible = false;

vsync = false;
log-level = "debug"
log-level = "info";

wintypes:
{
  	dropdown_menu = { opacity = 0.95;}
	tooltip = { fade = true; opacity = 0.95; focus = true; }
	popup_menu = { opacity = 0.95; animation = "none";}
    utility = { animation = "none"; };
};

