add_newline = false

format = """

[ ](bold white)$hostname$kubernetes$directory$git_branch$git_commit$git_state$git_status$docker_context$package$golang$helm$java$cmake$kotlin$lua$nim$nodejs$python$ruby$rust$aws$nix_shell$container
[ ➜ ](bold green)"""

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "blue bold"
trim_at = "."
disabled = false

[directory]
read_only = " "
truncation_length = 7
truncation_symbol = "…/"

[nix_shell]
symbol = " "

[container]
symbol = "📦"

[golang]
style = "blue"
symbol = " "

[lua]
symbol = " "

[cmake]
style = "green"
symbol = "△ "

[rust]
symbol = " "

[nodejs]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_status]
conflicted = "🏳 "
untracked = "🤷"
stashed = "📦"
modified = "📝"
renamed = "👅"
deleted = "🗑 "
