
;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================


[global/wm]
margin-bottom = 0
margin-top = 1
[colors]
background = #1f1f27
background-alt = #373646
foreground = #d8d2b2
primary = #9daccb
secondary = #668695
alert = #9daccb
disabled = #54546d

[bar/mainbar]
width = 100%
height = 28pt
radius = 8
dpi = 100
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 0pt
border-size = 10pt
border-bottom-size = 0
border-color = #00000000
padding-left = 0
padding-right = 2
module-margin = 2
separator-foreground = ${colors.disabled}
font-0 = JetBrains Mono Nerd Font;2
font-1 = NotoSansJP
modules-left = xworkspaces
modules-right =  pulseaudio filesystem  memory  temperature
modules-center = date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-volume-padding-left = 1
label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xwindow]
type = internal/xwindow
label = %class%
label-maxlen = 50
label-foreground = ${colors.disabled}

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true
label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.background}
label-active-underline= ${colors.background}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = / 
label-mounted =  %{F#9daccb}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}
label =  %gb_used%

[module/temperature]
type = internal/temperature
format-prefix = "󰢮 "
format-prefix-foreground = ${colors.primary}
hwmon-path = /sys/class/hwmon/hwmon1/temp1_input
interval = 5

[module/date]
type = internal/date
interval = 1
format-prefix-foreground = ${colors.primary}
date = %a %b %d, %H:%M
label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true
